### ISSUE TITLE
Parser raises error when `backup` is not defined

### ISSUE THREAD

**Issue by BCasaleiro** [wearemeight/primeight#5]
### Description
The parser fails if the table template does not have the `backup` field defined. 

### How to replicate it

Using the following template+script you are able to replicate this issue:

`thermostats.yaml`
```
version: 0.0.1

name: devices
keyspace: thermostats

columns:
  device_id:
    type: uuid
  temperature:
    type: float
  tsin:
    type: timestamp

generated_columns:
  day: tsin

query:

  base:
    required:
      id: device_id
    optional:
      - day

  time_based:
    required:
      time: day
    optional:
      - device_id
```

`main.py`
```
from primeight.parser import YamlParser

config = YamlParser.parse('thermostats.yaml')
```
