### ISSUE TITLE
Querying a materialized view using CassandraTable produces wrong statements 

### ISSUE THREAD

**Issue by BCasaleiro** [wearemeight/primeight#6]
### Description
When querying a materialized view using the CassandraTable object it produces wrong CQL statements.
This issue is caused by the way we transit the statements from the CassandraMaterializedView to the CassandraTable object, we should use the `CassandraMaterializedView._current_statements` instead of the `CassandraMaterializedView.statements`.

### How to replicate it

Using the following template+script you are able to replicate this issue:

`thermostats.yaml`
```
version: 0.0.1

name: devices
keyspace: thermostats

columns:
  device_id:
    type: uuid
  temperature:
    type: float
  tsin:
    type: timestamp

generated_columns:
  day: tsin

query:

  base:
    required:
      id: device_id
    optional:
      - day

  time_based:
    required:
      time: day
    optional:
      - device_id
```

`main.py`
```
from datetime import datetime

from primeight import CassandraKeyspace, CassandraTable
from primeight.parser import YamlParser


date = datetime(2020, 11, 20)

config = YamlParser.parse('thermostats.yaml')
keyspace = CassandraKeyspace(config)
table = CassandraTable(config, keyspace=keyspace)

statements = \
    table\
    .query('time_based') \
    .select(['temperature']) \
    .time(date, date) \
    .statements
print(statements)
```

### Result
`['SELECT * FROM thermostats.devices_time_based   ;']`

### Expected result
`['SELECT temperature FROM thermostats.devices_time_based WHERE day=1605830400000  ;']`
